// Generated by feather_bindings.sync_math_headers. Do not edit.
#pragma once

// A plugin compiles the engine's own math sources with reflection off:
// same fields, same layout, none of the ClassDB machinery.
#ifndef FEATHER_MATH_STANDALONE
#define FEATHER_MATH_STANDALONE
#endif
#include <feather_math/vector2.h>
#include <feather_math/vector3.h>
#include <feather_math/vector4.h>
#include <feather_math/quaternion.h>
#include <feather_math/color.h>
#include <feather_math/matrix.h>
#include <feather_math/precision.h>
