-- Engine target declarations, kept out of root xmake.lua so this file can be
-- includes()'d cross-repo without dragging in set_project()/set_version().
-- Thirdparty packages and feather_public_api must be includes()'d first.
--
-- os.scriptdir(), not os.projectdir(): the latter would resolve to a
-- CONSUMER's repo if this file were ever includes()'d cross-repo.
local FEATHER_ROOT = path.directory(os.scriptdir())

-- add_files() resolves relative paths against this file's own directory, not
-- the engine root, so every entry is joined with FEATHER_ROOT explicitly.
local function core_path(p) return path.join(FEATHER_ROOT, p) end

-- Generated by tools/codegen/generate_reflection.py; must be listed since
-- they don't exist on disk until codegen has run once.
local GENERATED_SOURCE = {}
for _, dir in ipairs({"framework", "main", "math", "rendering", "resources", "world"}) do
    table.insert(GENERATED_SOURCE, core_path("core/" .. dir .. "/register_" .. dir .. "_types.gen.cpp"))
end

-- ---- Main executable ------------------------------------------------------
target("feather")
    set_kind("binary")
    set_basename("feather")
    set_targetdir("$(builddir)/bin")

    add_files(core_path("core/**.cpp"))
    add_files(GENERATED_SOURCE, {always_added = true})

    add_files(core_path("modules/*.cpp"))
    add_includedirs(FEATHER_ROOT)

    -- Flips FEATHER_API to dllexport; consumer DLLs never define this, so
    -- they get dllimport and resolve against this exe's import lib.
    add_defines("FEATHER_BUILDING_ENGINE")

    if is_mode("debug", "releasedbg") then
        add_defines("BETA")
    end
    if is_mode("release") then
        add_defines("PRODUCTION")
    end

    add_deps("feather_public_api")
    -- Direct, not just via feather_public_api: see public_api.lua.
    add_deps("simplemath")
    add_packages("flecs", "assimp", "sdl3", "taywee_args")

    if is_plat("linux") then
        add_rpathdirs("$ORIGIN/lib", "$ORIGIN/runtime")
        -- Lets a dlopen'd project DLL resolve engine symbols at runtime.
        add_ldflags("-rdynamic", {force = true})
    end

    if is_plat("windows", "mingw") then
        -- project_settings.cpp calls SHGetFolderPathA directly; was only
        -- linking via sdl3's syslinks list, which broke once sdl3 went shared.
        add_syslinks("shell32")
    end

    if is_plat("mingw") then
        add_syslinks("stdc++exp")

        add_ldflags("-static-libgcc", "-static-libstdc++",
            "-Wl,-Bstatic,--whole-archive", "-lwinpthread", "-Wl,--no-whole-archive,-Bdynamic",
            -- GNU ld needs --out-implib explicitly (link.exe does this automatically).
            "-Wl,--out-implib,$(builddir)/bin/libfeather.a",
            {force = true})
    end

    -- A module's target is named after its directory under modules/. xmake
    -- ignores a dep with no matching target (e.g. a disabled module).
    for _, dir in ipairs(os.dirs(path.join(FEATHER_ROOT, "modules", "*"))) do
        add_deps(path.filename(dir))
    end

    add_rules("feather.deploy_shaders")
    add_rules("feather.deploy_shared_deps")
    
    -- import() only exists inside the hook's own closure, so codegen and flags are inlined here.
    on_config(function (target)
        import("feather_codegen")
        import("feather_flags")

        local module_dirs = {}
        if not is_plat("macosx") and has_config("enable_vex_renderer") then
            local vex_dir = path.join(FEATHER_ROOT, "modules", "vex_renderer")
            if os.isdir(vex_dir) then
                table.insert(module_dirs, vex_dir)
            end
        end
        feather_codegen.run_core_codegen(module_dirs, {feather_root = FEATHER_ROOT})

        cprint("${cyan}[codegen]${reset} generate_embedded_resources.py")
        os.vrunv("python3", {
            path.join(FEATHER_ROOT, "tools", "codegen", "generate_embedded_resources.py"),
        }, {curdir = FEATHER_ROOT})

        feather_flags.apply(target)
    end)
target_end()

-- ---- Modules (auto-discovered; re-opens the feather target) -------------
-- Must come after the executable target so module-specific rules and packages can be added to it.
includes(path.join(FEATHER_ROOT, "modules", "xmake.lua"))
