# =============================================================================
# Export targets for game projects to link against
# =============================================================================

# Get the runtime output directory for the current config
get_property(_isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(_isMultiConfig)
    set(_editor_location "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/$<CONFIG>/${PROJECT_NAME}.editor$<TARGET_FILE_SUFFIX:Editor>")
    set(_standalone_location "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/$<CONFIG>/${PROJECT_NAME}.standalone$<TARGET_FILE_SUFFIX:Standalone>")
else()
    set(_editor_location "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.editor$<TARGET_FILE_SUFFIX:Editor>")
    set(_standalone_location "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_NAME}.standalone$<TARGET_FILE_SUFFIX:Standalone>")
endif()

# Generate FeatherTargets.cmake with imported executable targets
# This file creates Feather::Editor and Feather::Standalone as imported executables
# with ENABLE_EXPORTS so game DLLs can link against their symbols
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/FeatherTargets-$<CONFIG>.cmake" CONTENT "\
# FeatherTargets.cmake - Auto-generated for config: $<CONFIG>
# Provides Feather::Editor and Feather::Standalone as imported executables

cmake_minimum_required(VERSION 3.15)

# Protect against multiple inclusion
if(TARGET Feather::Editor)
    return()
endif()

# Create imported target Feather::Editor
add_executable(Feather::Editor IMPORTED)
set_property(TARGET Feather::Editor PROPERTY ENABLE_EXPORTS 1)
set_target_properties(Feather::Editor PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS \"EDITOR_BUILD=1$<SEMICOLON>$<$<CONFIG:Debug>:BETA>$<SEMICOLON>$<$<CONFIG:Development>:BETA>\"
    IMPORTED_LOCATION \"${_editor_location}\"
)
set_property(TARGET Feather::Editor PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES \"${CMAKE_SOURCE_DIR}\" \"${CMAKE_SOURCE_DIR}/core\"
)

# Create imported target Feather::Standalone
add_executable(Feather::Standalone IMPORTED)
set_property(TARGET Feather::Standalone PROPERTY ENABLE_EXPORTS 1)
set_target_properties(Feather::Standalone PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS \"EDITOR_BUILD=0$<SEMICOLON>$<$<CONFIG:Debug>:BETA>$<SEMICOLON>$<$<CONFIG:Development>:BETA>\"
    IMPORTED_LOCATION \"${_standalone_location}\"
)
set_property(TARGET Feather::Standalone PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES \"${CMAKE_SOURCE_DIR}\" \"${CMAKE_SOURCE_DIR}/core\"
)

# Set per-config import locations for multi-config generators
set_property(TARGET Feather::Editor APPEND PROPERTY IMPORTED_CONFIGURATIONS $<UPPER_CASE:$<CONFIG>>)
set_target_properties(Feather::Editor PROPERTIES
    IMPORTED_LOCATION_$<UPPER_CASE:$<CONFIG>> \"${_editor_location}\"
)
set_property(TARGET Feather::Standalone APPEND PROPERTY IMPORTED_CONFIGURATIONS $<UPPER_CASE:$<CONFIG>>)
set_target_properties(Feather::Standalone PROPERTIES
    IMPORTED_LOCATION_$<UPPER_CASE:$<CONFIG>> \"${_standalone_location}\"
)
")

# Create FeatherTargets.cmake that includes the config-specific file
file(WRITE "${CMAKE_BINARY_DIR}/FeatherTargets.cmake" "\
# FeatherTargets.cmake - Auto-generated
# This file includes the appropriate config-specific targets file

# Try to include the config-specific file, with fallbacks
foreach(_config \${CMAKE_CONFIGURATION_TYPES} \${CMAKE_BUILD_TYPE} Release Debug Development)
    if(EXISTS \"\${CMAKE_CURRENT_LIST_DIR}/FeatherTargets-\${_config}.cmake\")
        include(\"\${CMAKE_CURRENT_LIST_DIR}/FeatherTargets-\${_config}.cmake\")
        break()
    endif()
endforeach()
")

# Generate FeatherConfig.cmake
file(WRITE "${CMAKE_BINARY_DIR}/FeatherConfig.cmake" "\
# FeatherConfig.cmake - Auto-generated by CMake
# This file is regenerated each time CMake runs on the engine.

cmake_minimum_required(VERSION 3.15)

# Include the exported targets
include(\"\${CMAKE_CURRENT_LIST_DIR}/FeatherTargets.cmake\")

# Store engine source directory for include paths
set(FEATHER_ENGINE_DIR \"${CMAKE_SOURCE_DIR}\")
set(FEATHER_BUILD_DIR \"\${CMAKE_CURRENT_LIST_DIR}\")

# Append third-party include directories to the imported targets
# These are needed for game projects to compile against engine headers
foreach(_target Feather::Editor Feather::Standalone)
    if(TARGET \${_target})
        set_property(TARGET \${_target} APPEND PROPERTY
            INTERFACE_INCLUDE_DIRECTORIES
                \"${CMAKE_SOURCE_DIR}/thirdparty/SimpleMath\"
                \"${CMAKE_SOURCE_DIR}/thirdparty/DirectXMath\"
                \"${CMAKE_BINARY_DIR}/_deps/directxmath-src/Inc\"
                \"${CMAKE_BINARY_DIR}/_deps/flecs-src/include\"
        )
    endif()
endforeach()

# Provide version info
set(Feather_VERSION \"${PROJECT_VERSION}\")
set(Feather_FOUND TRUE)
")

# Generate version file for find_package version checking
include(CMakePackageConfigHelpers)
write_basic_package_version_file(
        "${CMAKE_BINARY_DIR}/FeatherConfigVersion.cmake"
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion
)

# Register the package in CMake's user package registry
# This allows find_package(Feather) to work without specifying paths
# Registry location: ~/.cmake/packages/Feather (Linux/macOS) or Windows registry
file(WRITE "${CMAKE_BINARY_DIR}/FeatherPackageRegistry.cmake"
        "${CMAKE_BINARY_DIR}"
)
# Create the registry entry
set(_registry_dir "$ENV{HOME}/.cmake/packages/Feather")
file(MAKE_DIRECTORY "${_registry_dir}")
string(MD5 _hash "${CMAKE_BINARY_DIR}")
file(WRITE "${_registry_dir}/${_hash}" "${CMAKE_BINARY_DIR}")