option(STATIC_CPP "STATIC_CPP" ON)


if (WIN32)
    option(USE_LLVM "USE_LLVM" ON)
else()
    option(USE_LLVM "USE_LLVM" OFF)
endif()

if (${USE_LLVM})
    if (MSVC)
        if (${CMAKE_GENERATOR} == "Visual Studio 17 2022")
            set(CMAKE_GENERATOR_TOOLSET "ClangCl")
        else()
            set(CMAKE_C_COMPILER "clang-cl" CACHE STRING "The Cmake C Compiler")
            set(CMAKE_CXX_COMPILER "clang-cl" CACHE STRING "The Cmake CXX Compiler")
        endif()
    else()
        set(CMAKE_C_COMPILER "clang" CACHE STRING "The Cmake C Compiler")
        set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "The Cmake CXX Compiler")
    endif()
endif()